openapi: 3.0.0
info:
  title: MQTT Client API
  description: API to interact with MQTT broker for publishing and subscribing to topics.
  version: 1.0.0
  contact:
    name: Daniela Cáceres
paths:
  /publish:
    post:
      summary: Publish a message to an MQTT topic
      operationId: publishMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topic:
                  type: string
                  example: "daniela/topic"
                message:
                  type: string
                  example: "Hello World, my name is Daniela Cáceres!"
      responses:
        '200':
          description: Message successfully published
        '400':
          description: Invalid request
  /subscribe:
    get:
      summary: Subscribe to an MQTT topic
      operationId: subscribeTopic
      responses:
        '200':
          description: Successfully subscribed to the topic
        '400':
          description: Invalid request
externalDocs:
  description: Find the source code for this API on GitHub
  url: "https://github.com/Danyss09/architectural-patterns/tree/main/mqtt"
