# Imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY mqtt.py /app/mqtt.py
COPY requirements.txt /app/requirements.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto donde correrá Flask
EXPOSE 4000

# Comando por defecto para ejecutar el script
CMD ["python", "mqtt.py"]
